version: '3.8'

services:
  whisper-web:
    build: .
    container_name: whisper-web
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./transcriptions:/app/transcriptions
      - ./recorded_audio:/app/recorded_audio
      - whisper-models:/root/.cache/whisper
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      - DEVICE=${DEVICE:-auto}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-change_me}
      - HOST=0.0.0.0
      - PORT=5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - whisper-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: whisper-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - whisper-web
    networks:
      - whisper-network
    profiles:
      - with-nginx

networks:
  whisper-network:
    driver: bridge

volumes:
  whisper-models:
    driver: local